// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for fuchsia - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPbgmhZS5o1-3XdBjjaE1parZgDvdzRXY',
    appId: '1:4572425885:web:1c501834467ddd1cfd2e74',
    messagingSenderId: '4572425885',
    projectId: 'keystone-1424f',
    authDomain: 'keystone-1424f.firebaseapp.com',
    storageBucket: 'keystone-1424f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPbgmhZS5o1-3XdBjjaE1parZgDvdzRXY',
    appId: '1:4572425885:android:fbcc81d9c54fa7f3fd2e74',
    messagingSenderId: '4572425885',
    projectId: 'keystone-1424f',
    storageBucket: 'keystone-1424f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPbgmhZS5o1-3XdBjjaE1parZgDvdzRXY',
    appId: '1:4572425885:ios:b5d3156ad4f7253ffd2e74',
    messagingSenderId: '4572425885',
    projectId: 'keystone-1424f',
    storageBucket: 'keystone-1424f.appspot.com',
    iosBundleId: 'com.example.keystone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPbgmhZS5o1-3XdBjjaE1parZgDvdzRXY',
    appId: '1:4572425885:ios:b5d3156ad4f7253ffd2e74',
    messagingSenderId: '4572425885',
    projectId: 'keystone-1424f',
    storageBucket: 'keystone-1424f.appspot.com',
    iosBundleId: 'com.example.keystone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPbgmhZS5o1-3XdBjjaE1parZgDvdzRXY',
    appId: '1:4572425885:web:1c501834467ddd1cfd2e74',
    messagingSenderId: '4572425885',
    projectId: 'keystone-1424f',
    authDomain: 'keystone-1424f.firebaseapp.com',
    storageBucket: 'keystone-1424f.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDPbgmhZS5o1-3XdBjjaE1parZgDvdzRXY',
    appId: '1:4572425885:web:1c501834467ddd1cfd2e74',
    messagingSenderId: '4572425885',
    projectId: 'keystone-1424f',
    authDomain: 'keystone-1424f.firebaseapp.com',
    storageBucket: 'keystone-1424f.appspot.com',
  );
}
